<?php
# This file was automatically generated by the MediaWiki 1.36.2
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


function get_secret(string $secret){
    $file = file_get_contents("/run/secrets/".$secret);
    if($file !== false){
        return rtrim(file_get_contents("/run/secrets/".$secret), "\r\n");
    }else{
        throw new Exception('Error while loading configuration files');
    }
}
$wgServer = null;

function load_configs(){
    $files = array_filter(scandir('./LocalSettings.d/'), fn($file) => preg_match("/\d+\-[\w\-]+\.php$/",$file));
    foreach($files as $file){
        //print_r("loading_file: ".$file."\n");
        require_once './LocalSettings.d/'.$file;
    } 
}
load_configs();
//print("yso");
//die();